### PR TITLE
Add test script

### PR DESCRIPTION
**Pull request by PhysSong**
I think the script should have been improved more if we had more time, but I confirmed it gives the same results as the authors'.

### CODE REVIEW

**Comment by PhysSong** [comment]
@yycho0108 Please feel free to close this if you want.

**Comment by PhysSong** [comment]
Or if you want, I can extract metric functions only.

**Comment by yycho0108** [comment]
@PhysSong I think this is ok, since we're also computing the metrics only in the test script for now (i.e. not during training)

**Review by yycho0108 — APPROVED** [review]
LGTM.

**Pull request merged**
